# Generated by Django 6.0.4 on 2026-05-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maasbordrosu',
            name='bayram_gun',
            field=models.IntegerField(default=0, verbose_name='Bayram (Gün)'),
        ),
        migrations.AddField(
            model_name='maasbordrosu',
            name='fazla_mesai_saati',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Fazla Mesai (Saat)'),
        ),
        migrations.AddField(
            model_name='maasbordrosu',
            name='prim',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prim/İkramiye (TL)'),
        ),
        migrations.AddField(
            model_name='maasbordrosu',
            name='resmi_tatil_gun',
            field=models.IntegerField(default=0, verbose_name='Resmi Tatil (Gün)'),
        ),
    ]
