# Generated by Django 6.0.4 on 2026-05-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0002_maas_ek_odemeler'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='maas_tipi',
            field=models.CharField(choices=[('brut', 'Brüt Maaş'), ('net', 'Net Maaş')], default='brut', max_length=10, verbose_name='Maaş Tipi'),
        ),
    ]
