# Generated by Django 6.0.4 on 2026-05-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0003_personel_maas_tipi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='brut_maas',
            field=models.DecimalField(decimal_places=2, help_text="⚠️ DİKKAT: Maaş Tipi 'Brüt' seçildiyse BRÜT ücret (Örn: 33030), 'Net' seçildiyse NET ücret (Örn: 28075) yazınız.", max_digits=10, verbose_name='Maaş (TL)'),
        ),
    ]
