# Generated by Django 6.0.4 on 2026-05-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0004_personel_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='maasbordrosu',
            name='girilen_net_maas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net Maaş (TL)'),
        ),
    ]
