# Generated by Django 6.0.4 on 2026-05-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0005_bordro_girilen_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='maasbordrosu',
            name='bayram_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bayram Tutarı (TL)'),
        ),
        migrations.AddField(
            model_name='maasbordrosu',
            name='fazla_mesai_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fazla Mesai Tutarı (TL)'),
        ),
        migrations.AddField(
            model_name='maasbordrosu',
            name='resmi_tatil_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Resmi Tatil Tutarı (TL)'),
        ),
    ]
