# Generated by Django 6.0.4 on 2026-05-26 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0006_bordro_ek_odemeler_tutarlari'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaireKullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('daire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bina.daire', verbose_name='Daire')),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Daire Kullanıcısı',
                'verbose_name_plural': 'Daire Kullanıcıları',
            },
        ),
    ]
