# Generated by Django 6.0.4 on 2026-05-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0008_daire_kullanici_guncelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairekullanici',
            name='ilk_giris',
            field=models.BooleanField(default=True, verbose_name='İlk Giriş'),
        ),
        migrations.AddField(
            model_name='dairekullanici',
            name='sifre_sifirlandi_mi',
            field=models.BooleanField(default=False, verbose_name='Şifre Sıfırlandı mı?'),
        ),
    ]
