# Generated by Django 6.0.4 on 2026-05-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0009_daire_kullanici_ekle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gider',
            name='hesap_tipi',
            field=models.CharField(choices=[('esit', 'Eşit Bölüşüm (Ekstra Gider - Borç Olarak Yansır)'), ('hisse', 'Arsa Payına Göre (Ekstra Gider - Borç Olarak Yansır)'), ('brut_metrekare', 'Brüt Metrekareye Göre (Ekstra Gider - Borç Olarak Yansır)'), ('sabit_aidat', 'Sabit Aidat Kapsamında (Borç Yansıtma)')], default='esit', max_length=20, verbose_name='Dağıtım Şekli'),
        ),
    ]
