# Generated by Django 6.0.4 on 2026-05-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0010_gider_sabit_aidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='sabit_aidat_kesim_gunu',
            field=models.IntegerField(default=1, verbose_name='Sabit Aidat Kesim Günü'),
        ),
        migrations.AlterField(
            model_name='gider',
            name='tip',
            field=models.CharField(choices=[('elektrik', 'Elektrik'), ('su', 'Su'), ('dogalgaz', 'Yakıt / Doğalgaz'), ('yakıt', 'Yakıt/Kalorifer'), ('asansor', 'Asansör Bakım'), ('hidrofor', 'Hidrofor Bakım'), ('jenerator', 'Jeneratör Bakım'), ('yangin', 'Yangın Söndürme'), ('guvenlik', 'Güvenlik'), ('temizlik', 'Temizlik'), ('bahce', 'Bahçe Bakımı'), ('personel', 'Personel Maaşları'), ('sigorta', 'Sigorta'), ('vergi', 'Emlak Vergisi'), ('diger', 'Diğer')], max_length=20, verbose_name='Gider Tipi'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='sabit_aidat_aktif_mi',
            field=models.BooleanField(default=True, verbose_name='Sabit Aidat Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='sabit_aidat_miktari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aylık Sabit Aidat (TL)'),
        ),
    ]
