# Generated by Django 6.0.4 on 2026-05-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0011_sabit_aidat_ayarlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayarlari',
            name='depozito_ekle',
            field=models.BooleanField(default=True, verbose_name='Kalan Tutarı Depozitoya Ekle'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='gider_yuvarlama_aktif',
            field=models.BooleanField(default=False, verbose_name='Gider Yuvarlama Aktif'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='gider_yuvarlama_kat',
            field=models.IntegerField(default=10, help_text='10, 50, 100 TL gibi', verbose_name='Yuvarlama Katı (TL)'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='gider_yuvarlama_tip',
            field=models.CharField(choices=[('yukari', 'Yukarı Yuvarla'), ('asagi', 'Aşağı Yuvarla'), ('en_yakin', 'En Yakına Yuvarla')], default='yukari', max_length=10, verbose_name='Yuvarlama Tipi'),
        ),
    ]
