# Generated by Django 6.0.4 on 2026-06-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0012_yuvarlama_ayarlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='daireiliskisi',
            name='birincil_mi',
            field=models.BooleanField(default=True, help_text='Aidat ve borçlar bu kişiye yansır. Her dairede sadece 1 kişi birincil olabilir.', verbose_name='Birincil Kişi'),
        ),
    ]
