# Generated by Django 6.0.4 on 2026-06-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0013_daireiliskisi_birincil_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisi',
            name='diger_aciklama',
            field=models.CharField(blank=True, help_text="Kişi tipi 'Diğer' seçildiyse açıklama giriniz (Örn: Misafir, Hizmetli vb.)", max_length=200, verbose_name='Diğer Açıklaması'),
        ),
        migrations.AlterField(
            model_name='daireiliskisi',
            name='iliski_tipi',
            field=models.CharField(choices=[('ev_sahibi', 'Ev Sahibi'), ('kiraci', 'Kiracı'), ('aile_ferdi', 'Aile Ferdi (Eş/Çocuk/Anne/Baba)'), ('diger', 'Diğer')], max_length=20, verbose_name='İlişki Tipi'),
        ),
        migrations.AlterField(
            model_name='kisi',
            name='kisi_tipi',
            field=models.CharField(choices=[('ev_sahibi', 'Ev Sahibi'), ('kiraci', 'Kiracı'), ('aile_ferdi', 'Aile Ferdi (Eş/Çocuk/Anne/Baba)'), ('diger', 'Diğer')], max_length=20, verbose_name='Kişi Tipi'),
        ),
    ]
