# Generated by Django 6.0.4 on 2026-06-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0014_kisi_diger_aciklama_alter_daireiliskisi_iliski_tipi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidat',
            name='odeme_notu',
            field=models.TextField(blank=True, verbose_name='Ödeme Notu'),
        ),
        migrations.AddField(
            model_name='aidat',
            name='odeme_yapildi_mi',
            field=models.BooleanField(default=False, verbose_name='Ödeme Yapıldı mı?'),
        ),
        migrations.AddField(
            model_name='aidat',
            name='tahakkuk_tarihi',
            field=models.DateField(blank=True, help_text='Borcun doğduğu tarih (fatura tarihi)', null=True, verbose_name='Tahakkuk Tarihi'),
        ),
        migrations.AlterField(
            model_name='aidat',
            name='odendi_mi',
            field=models.BooleanField(default=False, verbose_name='Ödendi mi? (Eski)'),
        ),
    ]
