# Generated by Django 6.0.4 on 2026-06-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0015_aidat_odeme_notu_aidat_odeme_yapildi_mi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gider',
            options={},
        ),
        migrations.AddField(
            model_name='aidat',
            name='yuvarlama_farki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Yuvarlama Farkı'),
        ),
    ]
