# Generated by Django 6.0.4 on 2026-06-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0016_alter_gider_options_aidat_yuvarlama_farki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidat',
            name='odendi_mi',
        ),
    ]
