# Generated by Django 6.0.4 on 2026-06-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0017_remove_aidat_odendi_mi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gider',
            options={'ordering': ['-tarih'], 'verbose_name': 'Gider', 'verbose_name_plural': 'Giderler'},
        ),
        migrations.AddField(
            model_name='daire',
            name='muaf_mi',
            field=models.BooleanField(default=False, help_text='Yönetici daireleri için işaretlenir. Bu daireye aidat ve yakıt gideri yansıtılmaz.', verbose_name='Aidat/Yakıt Ödemelerinden Muaf'),
        ),
        migrations.AlterField(
            model_name='gider',
            name='fatura_donemi',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fatura Dönemi'),
        ),
    ]
