# Generated by Django 6.0.4 on 2026-06-04 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0018_alter_gider_options_daire_muaf_mi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiderTaksit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taksit_no', models.IntegerField(verbose_name='Taksit No')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taksit Tutarı')),
                ('tarih', models.DateField(verbose_name='Taksit Tarihi')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('gider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taksitler', to='bina.gider', verbose_name='Ana Gider')),
            ],
            options={
                'verbose_name': 'Gider Taksiti',
                'verbose_name_plural': 'Gider Taksitleri',
                'ordering': ['tarih', 'taksit_no'],
            },
        ),
    ]
