# Generated by Django 6.0.4 on 2026-06-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0019_gidertaksit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daire',
            name='muaf_mi',
        ),
        migrations.AddField(
            model_name='daire',
            name='demirbas_giderlerinden_muaf',
            field=models.BooleanField(default=False, help_text='Bu daireye asansör, hidrofor gibi demirbaş giderleri yansıtılmaz.', verbose_name='Demirbaş Giderlerinden Muaf'),
        ),
        migrations.AddField(
            model_name='daire',
            name='isletme_giderlerinden_muaf',
            field=models.BooleanField(default=False, help_text='Yönetici daireleri için işaretlenir. Bu daireye aidat, yakıt, elektrik, su gibi işletme giderleri yansıtılmaz.', verbose_name='İşletme Giderlerinden Muaf'),
        ),
    ]
