# Generated by Django 6.0.4 on 2026-06-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0020_remove_daire_muaf_mi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gider',
            name='muaf_daireler',
            field=models.ManyToManyField(blank=True, help_text='Bu giderden muaf tutulacak daireleri seçin. Seçili dairelere aidat yansıtılmaz.', related_name='muaf_oldugu_giderler', to='bina.daire', verbose_name='Muaf Daireler'),
        ),
    ]
