# Generated by Django 5.1.6 on 2026-06-13 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0021_gider_muaf_daireler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Site Adı')),
                ('slug', models.SlugField(help_text='Örn: sefa4-sitesi', unique=True, verbose_name='URL Kodu')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Siteler',
            },
        ),
        migrations.AddField(
            model_name='aidat',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='blok',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='daire',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='depozito',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='gider',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='kisi',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site', verbose_name='Site'),
        ),
    ]
