# Generated by Django 5.1.6 on 2026-06-17 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0022_site_aidat_site_blok_site_daire_site_depozito_site_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='logo',
        ),
        migrations.AddField(
            model_name='site',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yönettiği_siteler', to=settings.AUTH_USER_MODEL, verbose_name='Site Admini'),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL Kodu'),
        ),
    ]
