# Generated by Django 5.1.6 on 2026-06-27 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0023_remove_site_logo_site_admin_user_alter_site_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depozitohareket',
            options={'ordering': ['-tarih'], 'verbose_name': 'Depozito Hareketi', 'verbose_name_plural': 'Depozito Hareketleri'},
        ),
        migrations.AddField(
            model_name='depozitohareket',
            name='aidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depozito_hareketleri', to='bina.aidat', verbose_name='Bağlı Aidat'),
        ),
    ]
