# Generated by Django 5.1.6 on 2026-06-28 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0024_alter_depozitohareket_options_depozitohareket_aidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonelik',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site'),
        ),
        migrations.AddField(
            model_name='personel',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site'),
        ),
    ]
