# Generated by Django 5.1.6 on 2026-06-28 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0025_abonelik_site_fatura_site_personel_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonelik',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site', verbose_name='Site'),
        ),
    ]
