# Generated by Django 5.1.6 on 2026-06-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0026_alter_abonelik_site_alter_fatura_site_and_more'),
    ]

    operations = [
    ]
