# Generated by Django 5.1.6 on 2026-06-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0027_add_site_to_personel'),
    ]

    operations = [
    ]
