# Generated by Django 5.1.6 on 2026-06-28 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0028_add_site_to_siteayarlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='banka',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bina.site', verbose_name='Site'),
        ),
    ]
