# Generated by Django 5.1.6 on 2026-07-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bina', '0029_banka_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='depozito',
            name='ek_depozito_aciklama',
            field=models.TextField(blank=True, help_text='Ek depozito açıklaması', null=True, verbose_name='Ek Depozito Açıklaması'),
        ),
        migrations.AddField(
            model_name='depozito',
            name='ek_depozito_odeme_tarihi',
            field=models.DateField(blank=True, help_text='Ek depozito ödeme tarihi', null=True, verbose_name='Ek Depozito Ödeme Tarihi'),
        ),
        migrations.AddField(
            model_name='depozito',
            name='ek_depozito_odendi_mi',
            field=models.BooleanField(default=False, help_text='Ek depozito ödendi mi?', verbose_name='Ek Depozito Ödendi mi?'),
        ),
        migrations.AddField(
            model_name='depozito',
            name='ek_depozito_tutari',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dairelere yansıtılan ek depozito tutarı', max_digits=10, verbose_name='Ek Depozito Tutarı (TL)'),
        ),
        migrations.AddField(
            model_name='depozitohareket',
            name='ek_depozito_odendi_mi',
            field=models.BooleanField(default=False, help_text='Bu ek depozito ödendi mi?', verbose_name='Ek Depozito Ödendi mi?'),
        ),
        migrations.AlterField(
            model_name='depozitohareket',
            name='hareket_tipi',
            field=models.CharField(choices=[('ekleme', 'Ekleme (Fazla Ödeme)'), ('cikarma', 'Çıkarma (Mahsup)'), ('iade', 'İade'), ('ek_depozito', 'Ek Depozito')], max_length=20, verbose_name='Hareket Tipi'),
        ),
    ]
